development:
  dialect: postgres
  database: shop
  user: postgres
  password: postgres
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@db:5432/shop?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@db:5432/shop?sslmode=disable"}}